# Use Node.js latest base image
FROM node:22-alpine as development

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma Client code
RUN npx prisma generate

# Command to run the app
CMD [  "npm", "run", "dev" ]
