version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backoffice
    depends_on:
      - postgresdb
    networks:
      - backoffice-network
    ports:
      - '${PORT}:3333'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:${POSTGRES_PORT}/${POSTGRES_DB}
    restart: always

  postgresdb:
    image: postgres:15-alpine
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backoffice-network
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backoffice-network:

volumes:
  postgres_data:
