version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backoffice
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn start:dev'
    depends_on:
      - postgresdb
    networks:
      - backoffice-network
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backoffice-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backoffice-network:

volumes:
  postgres_data:
